### ISSUE TITLE
Some questions regarding the paper

### ISSUE THREAD

**Issue by birdx0810** [kexinhuang12345/clinicalBERT#10]
Hi, I'm a medical informatics student who is very interested in the paper and is recently taking a deeper look into the details of the paper. There are a few questions I hope you wouldn't mind answering.

1. In the unsupervised language modeling evaluation compared with a BERT pretrained on BookCorpus + WikiPedia, was the ClinicalBERT model already pretrained or trained from scratch?

2. In the Clinical/Medical Word Similarity task, the paper referenced Pedersen et al. (2016), which looks more like a survey on pharmacy practices. I couldn't find any details about the dataset used to evaluate the word similarity task, is there any way to have access to it?

Many thanks.

**Comment by kexinhuang12345** [comment]
Hi, sorry for the late reply. For 1, it is trained from the BERT checkpoint, but I would suggest also try pre-train from scratch using a newly trained tokenizer for clinical notes only since clinical notes are syntactically very different from the standard text in BERT tokenizer.

For 2. sorry, that was the wrong reference: here is the correct one:

T. Pedersen, S.V. Pakhomov, S. Patwardhan, C.G. Chute
Measures of semantic similarity and relatedness in the biomedical domain
J. Biomed. Informatics, 40 (3) (2007), pp. 288-299

Thanks!

**Comment by birdx0810** [comment]
Thanks mate~!
