### ISSUE TITLE
5-fold cross validation

### ISSUE THREAD

**Issue by rxlian** [kexinhuang12345/clinicalBERT#11]
I read the paper that the readmission classification was based on the 5-fold cross-validation but I didn't find the corresponding code. Could you please point out where is it?
Thanks.

**Comment by kexinhuang12345** [comment]
Hi sorry for the late reply!

I started this project as a class project and I didn't plan to run independent runs so I get one fold at the start. And then, I don't want to put extra time to retrain the one-fold again so instead of getting 5-fold directly, I mask the initial fold's validation and test set (20%) and use KFold algorithm to generate an additional 4-folds.

Here is the Jupyter notebook to reproduce the result, But I suggest you can use the sklearn's Kfold method, which is much simpler and the result should be comparable.

**Comment by kexinhuang12345** [comment]
[link](https://github.com/kexinhuang12345/clinicalBERT/blob/master/notebook/Dataset_Split.ipynb)
