### ISSUE TITLE
How to use ClinicalBERT for language modellling?

### ISSUE THREAD

**Issue by MoAbd** [kexinhuang12345/clinicalBERT#4]
Hello,
I need to predict next sentence in clinical note, How to clinicalBERT for this task?

**Comment by kexinhuang12345** [comment]
Hi sorry for the late reply. BERT uses masking language modeling instead of the classic directional predicting the next word manner. Hence, it is not directly designed for the sentence prediction task.   

I haven't done this task before, so sorry I couldn't be more helpful. But I can imagine using some generative model from the [CLS] latent embedding might work. Also, this work seems relevant:
https://arxiv.org/abs/1901.03859

**Comment by kexinhuang12345** [comment]
Also, check for GPT model: https://openai.com/blog/better-language-models/
